# Generated by Django 3.2.19 on 2023-06-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20230623_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tmb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
