# Generated by Django 3.2.19 on 2023-06-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_question_tmb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
