# Generated by Django 3.2.19 on 2023-09-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_auto_20230711_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gym_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='auth.Group'),
        ),
    ]
