# Generated by Django 3.2.19 on 2023-06-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20230623_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
