# Generated by Django 3.2.19 on 2023-06-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_question_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
