# Generated by Django 3.2.19 on 2023-07-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20230708_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_weight_calories', models.FloatField(blank=True, null=True)),
                ('mild_weight_loss', models.FloatField(blank=True, null=True)),
                ('wigth_loss', models.FloatField(blank=True, null=True)),
                ('extreme_weight_loss', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='calorie_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.calories'),
        ),
    ]
